[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "my_flit_init"
author = "Andrey Solomatin"
author-email = "Andrey_Solomatin@epam.com"
classifiers = ["License :: OSI Approved :: MIT License"]

